[versions]
agp = "8.2.0" # https://developer.android.com/build/releases/gradle-plugin
android-tools = "31.1.4"
androidx-activity-compose = "1.9.3" # https://developer.android.com/jetpack/androidx/releases/activity
asm-commons = "9.6" # https://asm.ow2.io/versions.html
compose = "1.6.11" # https://github.com/JetBrains/compose-multiplatform/releases
compose-lifecycle = "2.8.0" # https://github.com/JetBrains/compose-multiplatform/releases
kotlin = "1.9.23" # https://github.com/JetBrains/kotlin/releases
ktor = "2.3.13" # https://github.com/ktorio/ktor/releases
ktlint = "1.8.0" # https://github.com/pinterest/ktlint/releases
ktlint-gradle = "14.0.1" # https://github.com/JLLeitschuh/ktlint-gradle/releases
umbrellaaar = "2.3.0-SNAPSHOT" # https://github.com/tiper/UmbrellaAAR/releases

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
android-tools-common = { module = "com.android.tools:common", version.ref = "android-tools" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm-commons" }
compose-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-lifecycle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ktlint-gradle-plugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-gradle" }
ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
sample-export = { module = "io.github.tiper.sample:framework", version = "0.0.1" }


[plugins]
android-application-tiper = { id = "io.github.tiper.android.application" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-library-tiper = { id = "io.github.tiper.android.library" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-multiplatform-tiper = { id = "io.github.tiper.kotlin.multiplatform" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
umbrella-aar = { id = "io.github.tiper.umbrellaaar", version.ref = "umbrellaaar" }
umbrella-aar-pom = { id = "io.github.tiper.umbrellaaar.pom", version.ref = "umbrellaaar" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }
